create table public.clipnest_videos (
  id uuid not null default gen_random_uuid (),
  row_number integer null,
  platform text null,
  video_url text null,
  normalized_url text null,
  creator text null,
  title text null,
  summary text null,
  sentiment text null,
  tags text[] null,
  categories text[] null,
  transcript_url text null,
  transcript_preview text null,
  embedding extensions.vector null,
  created_at timestamp with time zone null default now(),
  published text null,
  venue text null,
  address text null,
  city text null,
  neighborhood text null,
  lat double precision null,
  lng double precision null,
  price text null,
  transcript_text text null,
  source text null default 'replit'::text,
  constraint clipnest_videos_pkey primary key (id)
) TABLESPACE pg_default;